# -*- coding: utf-8 -*-
"""PI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13VhvIz0ICnrdl8hwqtw-ESqSrNf-Kb0Y
"""

!pip install python-bcb

from bcb import sgs
selic = sgs.get({'salario-minimo':1619}, start='1995-01-01')
df=selic.reset_index()
print(df)

df.to_csv('Salario-minimo.csv')
df.to_excel('Salario-minimo.xlsx')

from bcb import sgs
ICF = sgs.get({'Indicador de Consumo das Famílias (IBGE)':433}, start='1980-01-01')
df=ICF.reset_index()
print(df)

df.to_csv('IPCA.csv')
df.to_excel('IPCA.xlsx')

from bcb import sgs
EF = sgs.get({'Endividamento das famílias':19882}, start='1995-01-01')
df=EF.reset_index()
print(df)

df.to_csv('Endividamento das famílias.csv')
df.to_excel('Endividamento das famílias.xlsx')

import pandas as pd

# Carregar os arquivos CSV
salario_minimo = pd.read_csv("Salario-minimo.csv")
ipca = pd.read_csv("IPCA.csv")
endividamento = pd.read_csv("Endividamento das famílias.csv")

# Remover espaços em branco dos nomes das colunas
salario_minimo.columns = salario_minimo.columns.str.strip()
ipca.columns = ipca.columns.str.strip()
endividamento.columns = endividamento.columns.str.strip()

# Renomear a coluna 'Date' para 'Data' para padronizar
salario_minimo.rename(columns={"Date": "Data"}, inplace=True)
ipca.rename(columns={"Date": "Data"}, inplace=True)
endividamento.rename(columns={"Date": "Data"}, inplace=True)

# Converter a coluna 'Data' para formato datetime para evitar problemas
salario_minimo["Data"] = pd.to_datetime(salario_minimo["Data"])
ipca["Data"] = pd.to_datetime(ipca["Data"])
endividamento["Data"] = pd.to_datetime(endividamento["Data"])

# Realizar a mesclagem dos datasets com base na coluna 'Data'
dados = salario_minimo.merge(ipca, on="Data").merge(endividamento, on="Data")

# Renomear colunas para maior clareza
dados.rename(columns={
    "salario-minimo": "Salario_Minimo",
    "Indicador de Consumo das Famílias (IBGE)": "IPCA",
    "Endividamento das famílias": "Endividamento"
}, inplace=True)

# Salvar o resultado em um novo arquivo CSV
dados.to_csv("dados_mesclados.csv", index=False)
dados.to_excel("dados_mesclados.xlsx", index=False)


print("Planilha combinada salva como 'dados_mesclados.csv'")